name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        version:
          - latest
          - v0.0.2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Init
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: init --skip-prompts
      - name: Check
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: check --debug
      - name: Release
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: help release
